### ISSUE TITLE
HDF5 format of TimeGF objects is incompatible with InchwormHPX

### ISSUE THREAD

**Issue by krivenko** [kleinhenz/Keldysh.jl#4]
https://github.com/kleinhenz/Keldysh.jl/blob/0cf9109a2649fe4173755b64fd91e4693c82b834/src/hdf5.jl#L94-L96

Would you mind saving also the `mesh/N` dataset needed for compatibility with the InchwormHPX GF library?

**Comment by kleinhenz** [comment]
closed by de83ddd2ddeab742bb516a20b62e0a0aa7792035
